{
 "title": "AMF dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "plmnid", "label": "PLMN", "query": { "query": "label_values(plmnid)" } },
   { "name": "snssai", "label": "S-NSSAI", "query": { "query": "label_values(snssai)" } }
  ]
 },
 "panels": [
  {
   "title": "AMF Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "amf_session{job=\"amf\"}",
     "legendFormat": "AMF Sessions"
    }
   ]
  },
  {
   "title": "Number of gNBs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnb{job=\"amf\"}",
     "legendFormat": "Number of gNBs"
    }
   ]
  },
  {
   "title": "AMF Initial Registration requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_reginitreq{job=\"amf\"}",
     "legendFormat": "AMF Initial Registration requests"
    },
    {
     "expr": "fivegs_amffunction_rm_reginitsucc{job=\"amf\"}",
     "legendFormat": "AMF successful Initial Registration requests"
    }
   ]
  },
  {
   "title": "Number of UEs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ran_ue{job=\"amf\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF Authentication requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "fivegs_amffunction_amf_authreq{job=\"amf\"}",
     "legendFormat": "AMF Authentication requests"
    },
    {
     "expr": "fivegs_amffunction_amf_authreject{job=\"amf\"}",
     "legendFormat": "AMF Authentication rejects"
    }
   ]
  },
  {
   "title": "AMF number of UEs in REGISTERED state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_registeredsubnbr{job=\"amf\"}",
     "legendFormat": "AMF number of UEs in REGISTERED state"
    },
    {
     "expr": "fivegs_amffunction_rm_registeredsubnbr{job=\"amf\",plmnid=\"00101\",snssai=\"1-000001\"}",
     "legendFormat": "AMF number of UEs in REGISTERED state for PLMN {{plmnid}} and S-NSSAI {{snssai}}"
    }
   ]
  }
 ]
}