db_uri: mongodb://db.open5gs.org/open5gs

logger:
  file:
    path: /var/log/open5gs/udr.log

global:

udr:
  sbi:
    server:
      - address: udr.open5gs.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.open5gs.org:80
      scp:
        - uri: http://scp.open5gs.org:80
      delegated:
        nrf:
          nfm: no
          disc: no
        scp:
          next: no
